### ISSUE TITLE
Compiling after making easy changes produces class not found message

### ISSUE THREAD

**Issue by mrwizard82d1** [magomimmo/modern-cljs#143]
Thanks for the great work on these tutorials. Not only do I better understand ClojureScript, but I also better understand modern Javascript.

I made the "easy" changes from Tutorial 06. However, once I begin editing the project.clj, file, I receive the following error message when running either "lein cljsbuild clean" or "lein cljsbuild once":

java.lang.Exception: Error loading D:\cygwin\home\l.jones\professional\projects\modern-cljs\project.clj
        at leiningen.core.project$read$fn__3326.invoke(project.clj:696)
        at leiningen.core.project$read.invoke(project.clj:693)
        at leiningen.core.project$read.invoke(project.clj:703)
        at leiningen.core.main$_main$fn__3092.invoke(main.clj:294)
        at leiningen.core.main$_main.doInvoke(main.clj:290)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:419)
        at clojure.lang.AFn.applyToHelper(AFn.java:163)
        at clojure.lang.Var.applyTo(Var.java:532)
        at clojure.core$apply.invoke(core.clj:617)
        at clojure.main$main_opt.invoke(main.clj:335)
        at clojure.main$main.doInvoke(main.clj:440)
        at clojure.lang.RestFn.invoke(RestFn.java:457)
        at clojure.lang.Var.invoke(Var.java:427)
        at clojure.lang.AFn.applyToHelper(AFn.java:172)
        at clojure.lang.Var.applyTo(Var.java:532)
        at clojure.main.main(main.java:37)
Caused by: java.lang.ClassNotFoundException: modern-cljs.core, compiling:(D:\cygwin\home\l.jones\professional\projects\modern-cljs\p
roject.clj:0:0)
  (other stuff elided)

Here's my project.clj file:

(defproject modern-cljs "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  
  ;; Clojure and ClojureScript source code paths
  :source-paths ["src/clj", "src/cljs"]
  :dependencies [[org.clojure/clojure "1.5.1"]
                 [org.clojure/clojurescript "0.0-2173"]
                 [compojure "1.1.6"]
                 [domina "1.0.3-SNAPSHOT"]]

  ;; Leiningen plugin to help building ClojureScript projects.
  :plugins [[lein-cljsbuild "1.0.2"]
            [lein-ring "0.8.10"]]

  ;; ClojureScript build configuration
  :cljsbuild {:builds
              ;; Generate login.js
              {:login
               {:source-paths ["src/cljs/login"]
                :compiler
                {:output-to "resources/public/js/login.js"
                 :optimization :whitespace
                 :pretty-print true}}}})

  ;; Ring configuration
  :ring {:handler modern-cljs.core/handler})

Although this file only has the "login target," I originally encountered this issue when I had both the "login target" and the "shopping target."

I only find a core file in the Clojure source (the line beginning with ./src):

$ find . -name 'core*'
./out/cljs/core.cljs
./out/cljs/core.js
./src/clj/modern_cljs/core.clj
./target/cljsbuild-compiler-0/cljs/core.cljs
./target/cljsbuild-compiler-0/cljs/core.js
./test/modern_cljs/core_test.clj

Because I'm on Windows and because I'm learning ClojureScript (although I'm familiar with Linux and use cygwin and I am familiar with Clojure), it is possible that this issue is caused by "user error."

Thanks.

**Comment by magomimmo** [comment]
the first edition of the modern-cljs series is no more active/supported.
