### ISSUE TITLE
Using the REPL doesn't really work very well....

### ISSUE THREAD

**Issue by IskaralPust** [magomimmo/modern-cljs#144]
I am having problems using the REPL. Sometimes it doesn't connect, sometimes it doesn't react until I reload the page and in chapter 5 calling (calculate) only results in this error: 

ClojureScript:modern-cljs.shopping> (calculate)
"Error evaluating:" (calculate) :as "modern_cljs.shopping.calculate.call(null)"
#<TypeError: Object #<error> has no method 'call'>
TypeError: Object #<error> has no method 'call'
    at calculate (http://localhost:3000/js/modern.js:28812:16)
    at eval (eval at <anonymous> (http://localhost:3000/js/modern.js:33937:260), <anonymous>:1:96)
    at eval (eval at <anonymous> (http://localhost:3000/js/modern.js:33937:260), <anonymous>:5:3)
    at http://localhost:3000/js/modern.js:33937:255
    at evaluate_javascript (http://localhost:3000/js/modern.js:33950:4)
    at Object.callback (http://localhost:3000/js/modern.js:34015:181)
    at goog.messaging.AbstractChannel.deliver (http://localhost:3000/js/modern.js:31764:13)
    at goog.net.xpc.CrossPageChannel.xpcDeliver (http://localhost:3000/js/modern.js:33306:14)
    at Function.goog.net.xpc.NativeMessagingTransport.messageReceived_ (http://localhost:3000/js/modern.js:32720:13)
    at goog.events.Listener.handleEvent (http://localhost:3000/js/modern.js:26716:26)
nil

Does anybody have any idea what the problem might be? This is all local on one machine so I assume it should run more smoothly.

**Comment by magomimmo** [comment]
the first edition of the modern-cljs series is no more active/supported.
